name: Publish gh-pages

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  website:
    runs-on: ubuntu-latest
    name: Build and publish
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      # build the website
      - env:
          DATA_URL: ${{ secrets.DATA_URL }}
        run: |
          echo $DATA_URL
          yarn
          yarn build
          touch out/.nojekyll


      # deploy build to gh-pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: out
